<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-cesar-flores/blob/main/Semana_2_Actividad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

César Flores Vivanco
A01173318

Reading files with open
funcion para crear una funcion de un archivo objeto y obtener la información de un txt file

ejemplo

file1= open("/resources/data/Example2.txt","r")

partes de la funcion
  # open - función
  # Example2.txt - file name
  # /resources/data - directorio
  # "w" - mode

los mode que hay son:

"r" reading
"w" writing
"a" appending

ejemplo para usar un file object

este es un ejemplo de un archivo para leer que se escribe en "r", el cual quiere decir en el primer ejemplo sobre información que viene en el archivo  sobre el nombre, ubicacion, tipo; si es r o w.

file1.name

/resources/data/Example2.txt

file.mode

"r"

file1.close

es para mencionar que ya terminó es importante poner el .close


#Esta es otra manera de hacerlo más facil 

with open("Example1.txt","r") as File1:
  quiere decir que abrirá el archivo y lo pondrá como File1 para facilitar su conecion

file_stuff=File1.read()
  en esta parte 

print(stuff)

# file_stuff=File1.read() y print(stuff) son indented block 
print(File1.closed)

print(file_stuff)

# Final del block, close file object


Cuando damos print a 

print(file_stuff)
this is line 1
this is line 2
this is line 3

resultado 

file_stuff:
this is line 1 \n this is line 2 \n this is line 3


with open("Example1.txt","r") as File1:

# Writing file with open

se usara open funtion para escribir en una fila, de hecho es similar al read "r"

file1= open("/resources/data/Example2.txt","w")

cuando agregamos las siguientes funciones quiere decir que agregará información al File1

File1.write("This is line A\n")
File1.write("This is line B\n")

es importante recordar que el with open _ as nos ayuda a convertir un archivo a una variable y las for _ in nos ayuda a generar loops

En este se puede usar read y write 

with open ("Example1.txt","r") as readfile:
  with open("Example3.txt","w") as writefile:
      for line in reafile:
        writefile.write(line)

Con este ejemplo podemos ejecutar ambos

# Pandas: Loanding data

es una herramienta muy popular para el analisis de datos

se comienza con el comando "import" siguiente con "pandas", ejemplo:

  import pandas 

despues se añadirá la carpeta de datos como una variables

   csv_path='file1_csv'

siguiente de

df=pandas.read_csv(csv_path)

pero hacerlo más facil se puede hacer de la siguiente manera ya que sino se debe hacer de formal manual y lleva más tiempo

import pandas as pd

csv_path='file1_csv'

df=pd.read_csv(csv_path)

# Dataframes
la abreviartura es df (dataframe) que es una tabla de los datos que viene de la hojas de calculo del archivo 

csv_path='file1_csv'

df=pd.read_csv(csv_path)

df.head()

In [4]:
#examen

import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()

    a   b
0  11  21
1  21  22
2  31  23

para crear una nueva columna se puede hacer lo sigueite

In [7]:
df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})
x=df[['b']]
x

    b
0  21
1  22
2  23

# Pandas - working with and Saving data

se puede usar metodos para buscar informacion dentro de los pandas. Además se puede cambiar el formato de guardado